#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Lint staged files
npx lint-staged

# Check TypeScript types
npx tsc --noEmit

# Run tests
npx jest --bail --findRelatedTests

# Format staged files
npx prettier --write .